# Generated by Django 4.2.20 on 2025-03-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='mobile2',
            field=models.CharField(max_length=300, null=True, verbose_name='Second Mobile'),
        ),
    ]
