# Generated by Django 4.2.20 on 2025-03-23 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0003_alter_voter_mobile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcandidate',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
        migrations.AddField(
            model_name='chaircandidate',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
        migrations.AddField(
            model_name='committeecandidate',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
        migrations.AddField(
            model_name='committeecandidate2',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
        migrations.AddField(
            model_name='voter',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
        migrations.AddField(
            model_name='voter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userRelatedUpdate', to=settings.AUTH_USER_MODEL),
        ),
    ]
