# Generated by Django 4.2.20 on 2025-03-23 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0004_boardcandidate_bywhat_chaircandidate_bywhat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('bywhat', models.CharField(max_length=300, null=True, verbose_name='ByWhat')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('sms', models.TextField(verbose_name='Text')),
                ('mob_b4', models.TextField(null=True, verbose_name='Mob_b4')),
                ('mob_aft', models.TextField(null=True, verbose_name='Mob_b4')),
                ('raw_sent', models.TextField(null=True, verbose_name='Sent')),
                ('raw_response', models.TextField(null=True, verbose_name='Sent')),
                ('messageId', models.TextField(null=True, verbose_name='Msg Id')),
                ('status', models.TextField(null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
