# Generated by Django 4.2.20 on 2025-03-23 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0005_smssent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViseCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('bywhat', models.CharField(max_length=300, null=True, verbose_name='ByWhat')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('memberNo', models.CharField(max_length=300, verbose_name='Member Registration No')),
                ('candidate_name', models.CharField(max_length=300, verbose_name='Candidate Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
