# Generated by Django 4.2.20 on 2025-03-24 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0006_visecandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votinglogin', to=settings.AUTH_USER_MODEL),
        ),
    ]
