# Generated by Django 4.2.20 on 2025-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0008_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='attended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
