# Generated by Django 4.2.20 on 2025-04-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0009_voter_attended_at_voter_is_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_on_meetin_option',
            field=models.BooleanField(default=True),
        ),
    ]
