# Generated by Django 4.2.20 on 2025-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0010_voter_is_on_meetin_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='end_attendance_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='publishing',
            name='open_for_special_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
