# Generated by Django 4.2.20 on 2025-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0011_publishing_end_attendance_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='start_attendance_time',
            field=models.DateTimeField(null=True),
        ),
    ]
