# Generated by Django 4.2.20 on 2025-04-04 13:07

import candidato.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0012_publishing_start_attendance_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matokeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which', models.CharField(choices=[('Bodi', 'Bodi'), ('Kamati', 'Kamati'), ('Mwenyekiti', 'Mwenyekiti')], max_length=300, verbose_name='Kichwa ')),
                ('title', models.TextField(verbose_name='Kichwa ')),
                ('maelezo', models.TextField(null=True, verbose_name='Maelezo ')),
                ('bodi_file', models.FileField(null=True, upload_to=candidato.models.content_matokeo_bodi, verbose_name='File ya bodi')),
                ('mkiti_file', models.FileField(null=True, upload_to=candidato.models.content_matokeo_mwenyekiti, verbose_name='File ya mwenyekiti')),
                ('kamati_file', models.FileField(null=True, upload_to=candidato.models.content_matokeo_kamati, verbose_name='File ya Kamati')),
            ],
        ),
    ]
