# Generated by Django 4.2.20 on 2025-04-04 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0013_matokeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matokeo',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
        migrations.AddField(
            model_name='matokeo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matokeo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='matokeo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matokeo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
