# Generated by Django 4.2.20 on 2025-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0014_matokeo_bywhat_matokeo_created_by_matokeo_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matokeo',
            name='bodi_file',
            field=models.FileField(null=True, upload_to='matokeo/bodi/', verbose_name='File ya bodi'),
        ),
    ]
