# Generated by Django 4.2.20 on 2025-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0015_alter_matokeo_bodi_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='matokeo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
