# Generated by Django 4.2.20 on 2025-04-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0016_matokeo_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='open_voting_for',
            field=models.CharField(choices=[('Bodi', 'Bodi'), ('Kamati', 'Kamati'), ('Mwenyekiti', 'Mwenyekeit')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='publishing',
            name='voting_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='publishing',
            name='voting_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
