# Generated by Django 4.2.20 on 2025-04-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0017_publishing_open_voting_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='stopAttendance',
            field=models.BooleanField(default=False),
        ),
    ]
