# Generated by Django 4.2.20 on 2025-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0018_publishing_stopattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='stopVoting',
            field=models.BooleanField(default=False),
        ),
    ]
