# Generated by Django 4.2.20 on 2025-04-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0019_publishing_stopvoting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishing',
            old_name='stopVoting',
            new_name='startVoting',
        ),
    ]
