# Generated by Django 4.2.20 on 2025-04-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0020_rename_stopvoting_publishing_startvoting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
