# Generated by Django 4.2.20 on 2025-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0021_voter_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='is_done',
        ),
        migrations.AddField(
            model_name='boardcandidate',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
