# Generated by Django 4.2.20 on 2025-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0022_remove_voter_is_done_boardcandidate_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcandidate',
            name='noVotes',
            field=models.IntegerField(default=0),
        ),
    ]
