# Generated by Django 4.2.20 on 2025-03-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memberNo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
