# Generated by Django 4.2.20 on 2025-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_user_memberno'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpassword',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bywhat',
            field=models.CharField(max_length=300, null=True, verbose_name='ByWhat'),
        ),
    ]
