# Generated by Django 4.2.20 on 2025-03-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_defaultpassword_bywhat_loginlog_bywhat_staff_bywhat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='memberNo',
        ),
    ]
