# Generated by Django 4.2.20 on 2025-03-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_rename_full_name_user_name_remove_user_memberno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='mobile',
        ),
    ]
