# Generated by Django 4.2.20 on 2025-03-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_rename_phone_number_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(null=True),
        ),
    ]
