# Generated by Django 4.2.20 on 2025-03-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0007_voter_user'),
        ('voting', '0002_committteevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committteevote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.committeecandidate'),
        ),
    ]
