# Generated by Django 4.2.20 on 2025-03-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0007_voter_user'),
        ('voting', '0004_chairvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairvote',
            name='chair_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.chaircandidate'),
        ),
    ]
