# Generated by Django 4.2.20 on 2025-03-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_chairvote_chair_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chairvote',
            old_name='chair_candidate',
            new_name='chair',
        ),
        migrations.RenameField(
            model_name='chairvote',
            old_name='vise_candidate',
            new_name='vise',
        ),
    ]
